apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-postgres
  labels:
    db: polar-postgres
spec:
  selector:
    matchLabels:
      db: polar-postgres
  template:
    metadata:
      labels:
        db: polar-postgres
    spec:
      containers:
        - name: polar-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: polardb_catalog
            #- name: POSTGRES_LISTEN_ADDRESS
            #  value: polar-postgres.springbook.svc.cluster.local
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: polar-postgres
  labels:
    db: polar-postgres
spec:
  type: ClusterIP
  selector:
    db: polar-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---

# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: polar-postgres
# subsets:
# - addresses:
#     - ip: 10.0.2.2
#   ports:
#     - port: 5432